[versions]
minSdkVersion = "26"
compilerSdkVersion = "36"
targetSdkVersion = "36"
jvmVersion = "21"

agp = "8.13.0"
kotlin = "2.2.0"
dokka = "1.8.10"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
composeBom = "2025.07.00"
material = "1.12.0"
composeMaterial = "1.7.6"

googleTruthVersion = "1.4.4"
mockKVersion = "1.14.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeMaterial"}

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
google-truth = { group = "com.google.truth", name="truth", version.ref = "googleTruthVersion" }
mockk = { group = "io.mockk", name="mockk", version.ref = "mockKVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka-documentation = { id = "org.jetbrains.dokka", version.ref = "dokka" }

